### ISSUE TITLE
negative buffersize in recv and Error during transmission

### ISSUE THREAD

**Issue by rgruyters** [jlusiardi/homekit_python#123]
I encounter sometimes an issue when my Hass receives an update from my bedside lamp, Xiaomi Bedside Lamp 2.

```
2019-03-27 19:52:02 ERROR (MainThread) [homeassistant.helpers.entity] Update for light.mjctd02yl fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.async_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/__init__.py", line 279, in async_update
    self._chars_to_poll
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/__init__.py", line 180, in get_characteristics
    **kwargs,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller/ip_implementation.py", line 192, in get_characteristics
    response = self.session.get(url)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller/ip_implementation.py", line 458, in get
    return self.sec_http.get(url)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 51, in get
    return self._handle_request(data)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 77, in _handle_request
    return self._read_response(self.timeout)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 108, in _read_response
    data = self.sock.recv(exp_len)
ValueError: negative buffersize in recv
```

```
2019-03-27 19:38:37 ERROR (MainThread) [homeassistant.helpers.entity] Update for light.mjctd02yl fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.async_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/__init__.py", line 279, in async_update
    self._chars_to_poll
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/__init__.py", line 180, in get_characteristics
    **kwargs,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller/ip_implementation.py", line 192, in get_characteristics
    response = self.session.get(url)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller/ip_implementation.py", line 458, in get
    return self.sec_http.get(url)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 51, in get
    return self._handle_request(data)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 77, in _handle_request
    return self._read_response(self.timeout)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 136, in _read_response
    raise exceptions.EncryptionError('Error during transmission.')
homekit.exceptions.EncryptionError: Error during transmission.
```

I had this issue with version 0.12.2, 0.12.3 and now also with 0.13.0 of homekit(_controller).

**Comment by jlusiardi** [comment]
Hey @rgruyters,
Does the lamp work fine with HASS besides those issues? I guess that perhaps the session times out on the lamp's side...
Regards
Joachim

**Comment by rgruyters** [comment]
@jlusiardi yeah it works fine. No issues so far.

**Comment by Jc2k** [comment]
I suspect this might be one of the things #114 is meant to fix?

**Comment by jlusiardi** [comment]
@Jc2k i will have a look

@rgruyters how often does this happen? Any chance you can try with the patch from #114?

**Comment by Jc2k** [comment]
I've applied those fixes to master and pushed it [here](https://github.com/Jc2k/homekit_python/tree/114_rebase) (not sure if #114 will be new enough for the version of HASS @rgruyters has).

**Comment by rgruyters** [comment]
@jlusiardi @Jc2k I should be able to test this. Will look into it tonight or tomorrow. (depends if I can find the time to do tonight)

**Comment by rgruyters** [comment]
I have updated the `secure_http.py` file and will do some test runs. Will let you know if it works. (or not)

**Comment by rgruyters** [comment]
So far so good. No new traceback messages.

@Jc2k can we create PR for Home Assistant to include the new version of homekit[IP] into homekit_controller?

**Comment by Jc2k** [comment]
We need to test this change a bit more and get it merged to master first, then do a tag. As soon as all that has happened I will do a PR (master has another fix I need soon too). 

There’s one more small change I’d like to sneak in before the next tag, so I’ll try and get a PR in for that tonight.

**Comment by jlusiardi** [comment]
I will have a look on the weekend! Is there any way we can include some kind of test for this in the test bench?

**Comment by Jc2k** [comment]
I've been wondering the same thing :-/ Maybe @mumblepins can help?

We should be able to test the change to `_handle_request` by making a put request with a large number of characteristics in it? And it looks like for testing `_read_response` we can use a get for a large number of characteristics?

But i'm not sure at all how to induce the negative buffer size error in a test...

**Comment by jlusiardi** [comment]
ah ok, sorry, I foremost meant how to test requests with more than 1k data. I didn't stumble over it, because my devices to so. Perhaps, we could start with a modification to `demoserver.py` to have a start.

**Comment by Jc2k** [comment]
Thinking about it, I did hack my local demoserver.py to have lots of accessories and there was an error with a thousand light bulbs but not a hundred. Let me see if I can recreate.

**Comment by Jc2k** [comment]
No, at 1000 lightbulbs on one bridge I get 65k of JSON from `/accessories`. It is truncated at 65385 bytes and won't parse. But I don't get a negative buffersize. So there must be another trigger for that.

**Comment by jlusiardi** [comment]
Ok, so we have 2 issues:
- to large requests like `/characteristics?id=1.2,1.3,...` with a vast number of ids (more than 1024bytes). This is fixed by #114 and could be tested with: 
```python
    def test_get_large_request(self):
        controller_socket, accessory_socket = socket.socketpair()

        key_c2a = b'S2}\xb1}-l\n\x83\xe5}\'U\xc0\x1b\x0f\x08%X\xfdu\x1f\x9el/\x9bZ"\xec5\xa5P'
        key_a2c = b'\x16\xab\xd3\xfe\x95{\xe56\x1fH\x81\xfd\x914\xa0@\xaa\x0e\xa6\xebw\xf2\xe3w:\x11/\x01\xbb;,\x1d'

        tthread = ResponseProvider(accessory_socket, key_c2a, key_a2c)
        tthread.start()

        with mock.patch('homekit.controller.ip_implementation.IpSession') as session:
            session.sock = controller_socket
            session.a2c_key = key_a2c
            session.c2a_key = key_c2a

            sh = SecureHttp(session, timeout=10)
            result = sh.get('/' + 1024 * 'a')

        controller_socket.close()
        accessory_socket.close()
        self.assertEqual(200, result.code)
        self.assertEqual(b'', result.body)
```
- your issue with the response getting truncated. can we create a test for that?

**Comment by Jc2k** [comment]
I have managed to recreate the exception synthetically! I still don't know how this happens "in the wild", though.

See [this commit](https://github.com/jlusiardi/homekit_python/commit/2f05c6776dbcd51e164c7dd3e4756d2556066eb7). I modified ResponseProvider

The three blocks are:

```python
data = [
    'HTTP/1.1 200 OK\r\nContent-Length: 1025\r\n\r\n',
    ' ' * 946,
    ' ' * 79
]
```

Observations:

 * If the 2nd block is between 1 byte and 946 bytes and there is a 3rd block this happens.
 * If the 2nd block is between 1 byte and 946 bytes and there isn't a 3rd block there is NO negative read exception.
 * If the 2nd block is 947 bytes this error doesn't happen
 * If the 2nd block is 947 bytes and the 3rd block is 78 bytes then the test fully passes.
 * In terms of negative read exceptions, the size of the 3rd block seems unimportant - 1 byte, 3 bytes, 100 bytes, 1024 bytes all trigger the response. 

And as hoped, the test *does* pass if its run on my rebase of #114. So this test and @rgruyters's testing seem to indicate #114 fixes or at least improves the negative read situation.
